import type { IntakeSeed, SourceFact } from "@ple/types";
import { fact, intakeSubject, nowIso, seedIdentity, slug } from "../lib";

const OFFICIAL_RECORDS_URL = "https://onlineservices.miamidadeclerk.gov/officialrecords";

export async function fetchDeedEvidenceFacts(runId: string, seed: IntakeSeed): Promise<SourceFact[]> {
  const fetchedAt = nowIso();
  const rawId = `deed-history:${slug(seedIdentity(seed))}`;
  const subject = intakeSubject(seed);

  return [
    fact({
      runId,
      source: "official_records",
      rawId: `${rawId}:status`,
      fetchedAt,
      county: seed.county,
      subject,
      factType: "deed_history_status",
      value: "manual_or_browser_extraction_required",
      confidence: 0.25,
      sourceUrl: OFFICIAL_RECORDS_URL,
      reviewFlags: ["MISSING_DEED_FACT", "SOURCE_EVIDENCE_REQUIRED", "HUMAN_REVIEW_REQUIRED", "NO_ENRICHMENT_RUN"],
    }),
    fact({
      runId,
      source: "official_records",
      rawId: `${rawId}:latest-deed`,
      fetchedAt,
      county: seed.county,
      subject,
      factType: "latest_deed",
      value: null,
      confidence: 0,
      sourceUrl: OFFICIAL_RECORDS_URL,
      reviewFlags: ["MISSING_DEED_FACT", "SOURCE_EVIDENCE_REQUIRED", "HUMAN_REVIEW_REQUIRED", "NO_ENRICHMENT_RUN"],
    }),
    fact({
      runId,
      source: "official_records",
      rawId: `${rawId}:or-book-page`,
      fetchedAt,
      county: seed.county,
      subject,
      factType: "or_book_page",
      value: null,
      confidence: 0,
      sourceUrl: OFFICIAL_RECORDS_URL,
      reviewFlags: ["MISSING_OR_BOOK_PAGE_FACT", "SOURCE_EVIDENCE_REQUIRED", "HUMAN_REVIEW_REQUIRED", "NO_ENRICHMENT_RUN"],
    }),
    fact({
      runId,
      source: "official_records",
      rawId: `${rawId}:last-sale-date`,
      fetchedAt,
      county: seed.county,
      subject,
      factType: "last_sale_date",
      value: null,
      confidence: 0,
      sourceUrl: OFFICIAL_RECORDS_URL,
      reviewFlags: ["MISSING_RECENT_SALE_FACT", "SOURCE_EVIDENCE_REQUIRED", "HUMAN_REVIEW_REQUIRED", "NO_ENRICHMENT_RUN"],
    }),
    fact({
      runId,
      source: "official_records",
      rawId: `${rawId}:ownership-activity`,
      fetchedAt,
      county: seed.county,
      subject,
      factType: "ownership_activity_note",
      value: null,
      confidence: 0,
      sourceUrl: OFFICIAL_RECORDS_URL,
      reviewFlags: ["MISSING_DEED_FACT", "SOURCE_EVIDENCE_REQUIRED", "HUMAN_REVIEW_REQUIRED", "NO_ENRICHMENT_RUN"],
    }),
    fact({
      runId,
      source: "official_records",
      rawId: `${rawId}:mortgage`,
      fetchedAt,
      county: seed.county,
      subject,
      factType: "mortgage_signal",
      value: null,
      confidence: 0,
      sourceUrl: OFFICIAL_RECORDS_URL,
      reviewFlags: ["MISSING_TITLE_FACT", "SOURCE_EVIDENCE_REQUIRED", "HUMAN_REVIEW_REQUIRED", "NO_ENRICHMENT_RUN"],
    }),
    fact({
      runId,
      source: "official_records",
      rawId: `${rawId}:lien`,
      fetchedAt,
      county: seed.county,
      subject,
      factType: "lien_signal",
      value: null,
      confidence: 0,
      sourceUrl: OFFICIAL_RECORDS_URL,
      reviewFlags: ["MISSING_TITLE_FACT", "SOURCE_EVIDENCE_REQUIRED", "HUMAN_REVIEW_REQUIRED", "NO_ENRICHMENT_RUN"],
    }),
    fact({
      runId,
      source: "official_records",
      rawId: `${rawId}:lis-pendens`,
      fetchedAt,
      county: seed.county,
      subject,
      factType: "lis_pendens_signal",
      value: null,
      confidence: 0,
      sourceUrl: OFFICIAL_RECORDS_URL,
      reviewFlags: ["MISSING_TITLE_FACT", "SOURCE_EVIDENCE_REQUIRED", "HUMAN_REVIEW_REQUIRED", "NO_ENRICHMENT_RUN"],
    }),
    fact({
      runId,
      source: "official_records",
      rawId: `${rawId}:foreclosure`,
      fetchedAt,
      county: seed.county,
      subject,
      factType: "foreclosure_signal",
      value: null,
      confidence: 0,
      sourceUrl: OFFICIAL_RECORDS_URL,
      reviewFlags: ["MISSING_TITLE_FACT", "SOURCE_EVIDENCE_REQUIRED", "HUMAN_REVIEW_REQUIRED", "NO_ENRICHMENT_RUN"],
    }),
    fact({
      runId,
      source: "official_records",
      rawId: `${rawId}:adverse-possession`,
      fetchedAt,
      county: seed.county,
      subject,
      factType: "adverse_possession_signal",
      value: null,
      confidence: 0,
      sourceUrl: OFFICIAL_RECORDS_URL,
      reviewFlags: ["MISSING_ADVERSE_POSSESSION_FACT", "SOURCE_EVIDENCE_REQUIRED", "HUMAN_REVIEW_REQUIRED", "NO_ENRICHMENT_RUN"],
    }),
  ];
}
